// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package db

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_key (id, key, name, description, user_id, enabled)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, "key", name, description, user_id, enabled, created_at, last_used_at
`

type CreateAPIKeyParams struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      string         `json:"user_id"`
	Enabled     sql.NullInt64  `json:"enabled"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg *CreateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.Enabled,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_key WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one

SELECT id, "key", name, description, user_id, enabled, created_at, last_used_at FROM api_key WHERE id = ?
`

// API key queries
func (q *Queries) GetAPIKey(ctx context.Context, id string) (*ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const getAPIKeyByKey = `-- name: GetAPIKeyByKey :one
SELECT id, "key", name, description, user_id, enabled, created_at, last_used_at FROM api_key WHERE key = ?
`

func (q *Queries) GetAPIKeyByKey(ctx context.Context, key string) (*ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByKey, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const getAPIKeyByKeyEnabled = `-- name: GetAPIKeyByKeyEnabled :one
SELECT id, "key", name, description, user_id, enabled, created_at, last_used_at FROM api_key WHERE key = ? AND enabled = 1
`

func (q *Queries) GetAPIKeyByKeyEnabled(ctx context.Context, key string) (*ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByKeyEnabled, key)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, "key", name, description, user_id, enabled, created_at, last_used_at FROM api_key ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]*ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.Enabled,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_key
SET name = ?, description = ?, user_id = ?, enabled = ?
WHERE id = ?
RETURNING id, "key", name, description, user_id, enabled, created_at, last_used_at
`

type UpdateAPIKeyParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      string         `json:"user_id"`
	Enabled     sql.NullInt64  `json:"enabled"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg *UpdateAPIKeyParams) (*ApiKey, error) {
	row := q.db.QueryRowContext(ctx, updateAPIKey,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.Enabled,
		arg.ID,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.Enabled,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_key SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
