// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: header.sql

package db

import (
	"context"
)

const createHeader = `-- name: CreateHeader :one
INSERT INTO header (route_id, key, value)
VALUES (?, ?, ?)
RETURNING id, route_id, "key", value, created_at
`

type CreateHeaderParams struct {
	RouteID string `json:"route_id"`
	Key     string `json:"key"`
	Value   string `json:"value"`
}

func (q *Queries) CreateHeader(ctx context.Context, arg *CreateHeaderParams) (*Header, error) {
	row := q.db.QueryRowContext(ctx, createHeader, arg.RouteID, arg.Key, arg.Value)
	var i Header
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteHeader = `-- name: DeleteHeader :exec
DELETE FROM header WHERE id = ?
`

func (q *Queries) DeleteHeader(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHeader, id)
	return err
}

const deleteHeadersByRouteID = `-- name: DeleteHeadersByRouteID :exec
DELETE FROM header WHERE route_id = ?
`

func (q *Queries) DeleteHeadersByRouteID(ctx context.Context, routeID string) error {
	_, err := q.db.ExecContext(ctx, deleteHeadersByRouteID, routeID)
	return err
}

const getHeader = `-- name: GetHeader :one

SELECT id, route_id, "key", value, created_at FROM header WHERE id = ?
`

// Header queries
func (q *Queries) GetHeader(ctx context.Context, id int64) (*Header, error) {
	row := q.db.QueryRowContext(ctx, getHeader, id)
	var i Header
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
	)
	return &i, err
}

const getHeadersByRouteID = `-- name: GetHeadersByRouteID :many
SELECT id, route_id, "key", value, created_at FROM header WHERE route_id = ? ORDER BY key
`

func (q *Queries) GetHeadersByRouteID(ctx context.Context, routeID string) ([]*Header, error) {
	rows, err := q.db.QueryContext(ctx, getHeadersByRouteID, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Header{}
	for rows.Next() {
		var i Header
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeader = `-- name: UpdateHeader :one
UPDATE header SET key = ?, value = ? WHERE id = ?
RETURNING id, route_id, "key", value, created_at
`

type UpdateHeaderParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateHeader(ctx context.Context, arg *UpdateHeaderParams) (*Header, error) {
	row := q.db.QueryRowContext(ctx, updateHeader, arg.Key, arg.Value, arg.ID)
	var i Header
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
	)
	return &i, err
}
