// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type ApiKey struct {
	ID          string         `json:"id"`
	Key         string         `json:"key"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UserID      string         `json:"user_id"`
	Enabled     sql.NullInt64  `json:"enabled"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	LastUsedAt  sql.NullTime   `json:"last_used_at"`
}

type DefaultRateLimit struct {
	ID                int64 `json:"id"`
	RequestsPerSecond int64 `json:"requests_per_second"`
	Burst             int64 `json:"burst"`
}

type Header struct {
	ID        int64        `json:"id"`
	RouteID   string       `json:"route_id"`
	Key       string       `json:"key"`
	Value     string       `json:"value"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type IpWhitelist struct {
	ID          string         `json:"id"`
	IpCidr      string         `json:"ip_cidr"`
	Description sql.NullString `json:"description"`
	Enabled     sql.NullInt64  `json:"enabled"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type RateLimit struct {
	ID                int64        `json:"id"`
	UserID            string       `json:"user_id"`
	RequestsPerSecond int64        `json:"requests_per_second"`
	Burst             int64        `json:"burst"`
	CreatedAt         sql.NullTime `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
}

type Route struct {
	ID               string        `json:"id"`
	Pattern          string        `json:"pattern"`
	Identifier       string        `json:"identifier"`
	IdentifierSource string        `json:"identifier_source"`
	TargetUrl        string        `json:"target_url"`
	Enabled          sql.NullInt64 `json:"enabled"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
}

type TlsConfig struct {
	ID        int64          `json:"id"`
	Enabled   sql.NullInt64  `json:"enabled"`
	CertFile  sql.NullString `json:"cert_file"`
	KeyFile   sql.NullString `json:"key_file"`
	AutoCert  sql.NullInt64  `json:"auto_cert"`
	Domains   sql.NullString `json:"domains"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
