// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg *CreateAPIKeyParams) (*ApiKey, error)
	CreateHeader(ctx context.Context, arg *CreateHeaderParams) (*Header, error)
	CreateRoute(ctx context.Context, arg *CreateRouteParams) (*Route, error)
	CreateWhitelistEntry(ctx context.Context, arg *CreateWhitelistEntryParams) (*IpWhitelist, error)
	DeleteAPIKey(ctx context.Context, id string) error
	DeleteHeader(ctx context.Context, id int64) error
	DeleteHeadersByRouteID(ctx context.Context, routeID string) error
	DeleteRoute(ctx context.Context, id string) error
	DeleteWhitelistEntry(ctx context.Context, id string) error
	// API key queries
	GetAPIKey(ctx context.Context, id string) (*ApiKey, error)
	GetAPIKeyByKey(ctx context.Context, key string) (*ApiKey, error)
	GetAPIKeyByKeyEnabled(ctx context.Context, key string) (*ApiKey, error)
	// Header queries
	GetHeader(ctx context.Context, id int64) (*Header, error)
	GetHeadersByRouteID(ctx context.Context, routeID string) ([]*Header, error)
	// Route queries
	GetRoute(ctx context.Context, id string) (*Route, error)
	GetRouteByIdentifier(ctx context.Context, identifier string) (*Route, error)
	// TLS config queries
	GetTLSConfig(ctx context.Context) (*TlsConfig, error)
	GetWhitelistByIP(ctx context.Context, ipCidr string) (*IpWhitelist, error)
	// IP whitelist queries
	GetWhitelistEntry(ctx context.Context, id string) (*IpWhitelist, error)
	ListAPIKeys(ctx context.Context) ([]*ApiKey, error)
	ListEnabledRoutes(ctx context.Context) ([]*Route, error)
	ListEnabledWhitelist(ctx context.Context) ([]*IpWhitelist, error)
	ListRoutes(ctx context.Context) ([]*Route, error)
	ListWhitelist(ctx context.Context) ([]*IpWhitelist, error)
	UpdateAPIKey(ctx context.Context, arg *UpdateAPIKeyParams) (*ApiKey, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id string) error
	UpdateHeader(ctx context.Context, arg *UpdateHeaderParams) (*Header, error)
	UpdateRoute(ctx context.Context, arg *UpdateRouteParams) (*Route, error)
	UpdateWhitelistEntry(ctx context.Context, arg *UpdateWhitelistEntryParams) (*IpWhitelist, error)
	UpsertTLSConfig(ctx context.Context, arg *UpsertTLSConfigParams) error
}

var _ Querier = (*Queries)(nil)
