// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limit.sql

package db

import (
	"context"
)

const createRateLimit = `-- name: CreateRateLimit :one
INSERT INTO rate_limit (user_id, requests_per_second, burst)
VALUES (?, ?, ?)
RETURNING id, user_id, requests_per_second, burst, created_at, updated_at
`

type CreateRateLimitParams struct {
	UserID            string `json:"user_id"`
	RequestsPerSecond int64  `json:"requests_per_second"`
	Burst             int64  `json:"burst"`
}

func (q *Queries) CreateRateLimit(ctx context.Context, arg *CreateRateLimitParams) (*RateLimit, error) {
	row := q.db.QueryRowContext(ctx, createRateLimit, arg.UserID, arg.RequestsPerSecond, arg.Burst)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRateLimit = `-- name: DeleteRateLimit :exec
DELETE FROM rate_limit WHERE user_id = ?
`

func (q *Queries) DeleteRateLimit(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRateLimit, userID)
	return err
}

const getDefaultRateLimit = `-- name: GetDefaultRateLimit :one
SELECT id, requests_per_second, burst FROM default_rate_limit WHERE id = 1
`

func (q *Queries) GetDefaultRateLimit(ctx context.Context) (*DefaultRateLimit, error) {
	row := q.db.QueryRowContext(ctx, getDefaultRateLimit)
	var i DefaultRateLimit
	err := row.Scan(&i.ID, &i.RequestsPerSecond, &i.Burst)
	return &i, err
}

const getRateLimit = `-- name: GetRateLimit :one

SELECT id, user_id, requests_per_second, burst, created_at, updated_at FROM rate_limit WHERE id = ?
`

// Rate limit queries
func (q *Queries) GetRateLimit(ctx context.Context, id int64) (*RateLimit, error) {
	row := q.db.QueryRowContext(ctx, getRateLimit, id)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRateLimitByUserID = `-- name: GetRateLimitByUserID :one
SELECT id, user_id, requests_per_second, burst, created_at, updated_at FROM rate_limit WHERE user_id = ?
`

func (q *Queries) GetRateLimitByUserID(ctx context.Context, userID string) (*RateLimit, error) {
	row := q.db.QueryRowContext(ctx, getRateLimitByUserID, userID)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRateLimits = `-- name: ListRateLimits :many
SELECT id, user_id, requests_per_second, burst, created_at, updated_at FROM rate_limit ORDER BY user_id
`

func (q *Queries) ListRateLimits(ctx context.Context) ([]*RateLimit, error) {
	rows, err := q.db.QueryContext(ctx, listRateLimits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RateLimit{}
	for rows.Next() {
		var i RateLimit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestsPerSecond,
			&i.Burst,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRateLimit = `-- name: UpdateRateLimit :one
UPDATE rate_limit
SET requests_per_second = ?, burst = ?, updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
RETURNING id, user_id, requests_per_second, burst, created_at, updated_at
`

type UpdateRateLimitParams struct {
	RequestsPerSecond int64  `json:"requests_per_second"`
	Burst             int64  `json:"burst"`
	UserID            string `json:"user_id"`
}

func (q *Queries) UpdateRateLimit(ctx context.Context, arg *UpdateRateLimitParams) (*RateLimit, error) {
	row := q.db.QueryRowContext(ctx, updateRateLimit, arg.RequestsPerSecond, arg.Burst, arg.UserID)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestsPerSecond,
		&i.Burst,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertDefaultRateLimit = `-- name: UpsertDefaultRateLimit :exec
INSERT INTO default_rate_limit (id, requests_per_second, burst)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET requests_per_second = ?, burst = ?
`

type UpsertDefaultRateLimitParams struct {
	RequestsPerSecond int64 `json:"requests_per_second"`
	Burst             int64 `json:"burst"`
}

func (q *Queries) UpsertDefaultRateLimit(ctx context.Context, arg *UpsertDefaultRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, upsertDefaultRateLimit, arg.RequestsPerSecond, arg.Burst)
	return err
}
