// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route.sql

package db

import (
	"context"
	"database/sql"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO route (id, pattern, identifier, identifier_source, target_url, enabled)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, pattern, identifier, identifier_source, target_url, enabled, created_at, updated_at
`

type CreateRouteParams struct {
	ID               string        `json:"id"`
	Pattern          string        `json:"pattern"`
	Identifier       string        `json:"identifier"`
	IdentifierSource string        `json:"identifier_source"`
	TargetUrl        string        `json:"target_url"`
	Enabled          sql.NullInt64 `json:"enabled"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg *CreateRouteParams) (*Route, error) {
	row := q.db.QueryRowContext(ctx, createRoute,
		arg.ID,
		arg.Pattern,
		arg.Identifier,
		arg.IdentifierSource,
		arg.TargetUrl,
		arg.Enabled,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Identifier,
		&i.IdentifierSource,
		&i.TargetUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM route WHERE id = ?
`

func (q *Queries) DeleteRoute(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRoute, id)
	return err
}

const getRoute = `-- name: GetRoute :one

SELECT id, pattern, identifier, identifier_source, target_url, enabled, created_at, updated_at FROM route WHERE id = ?
`

// Route queries
func (q *Queries) GetRoute(ctx context.Context, id string) (*Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Identifier,
		&i.IdentifierSource,
		&i.TargetUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRouteByIdentifier = `-- name: GetRouteByIdentifier :one
SELECT id, pattern, identifier, identifier_source, target_url, enabled, created_at, updated_at FROM route WHERE identifier = ? AND enabled = 1
`

func (q *Queries) GetRouteByIdentifier(ctx context.Context, identifier string) (*Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByIdentifier, identifier)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Identifier,
		&i.IdentifierSource,
		&i.TargetUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listEnabledRoutes = `-- name: ListEnabledRoutes :many
SELECT id, pattern, identifier, identifier_source, target_url, enabled, created_at, updated_at FROM route WHERE enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListEnabledRoutes(ctx context.Context) ([]*Route, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Identifier,
			&i.IdentifierSource,
			&i.TargetUrl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, pattern, identifier, identifier_source, target_url, enabled, created_at, updated_at FROM route ORDER BY created_at DESC
`

func (q *Queries) ListRoutes(ctx context.Context) ([]*Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Route{}
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Identifier,
			&i.IdentifierSource,
			&i.TargetUrl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE route
SET pattern = ?, identifier = ?, identifier_source = ?, target_url = ?, enabled = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, pattern, identifier, identifier_source, target_url, enabled, created_at, updated_at
`

type UpdateRouteParams struct {
	Pattern          string        `json:"pattern"`
	Identifier       string        `json:"identifier"`
	IdentifierSource string        `json:"identifier_source"`
	TargetUrl        string        `json:"target_url"`
	Enabled          sql.NullInt64 `json:"enabled"`
	ID               string        `json:"id"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg *UpdateRouteParams) (*Route, error) {
	row := q.db.QueryRowContext(ctx, updateRoute,
		arg.Pattern,
		arg.Identifier,
		arg.IdentifierSource,
		arg.TargetUrl,
		arg.Enabled,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Identifier,
		&i.IdentifierSource,
		&i.TargetUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
