// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tls.sql

package db

import (
	"context"
	"database/sql"
)

const getTLSConfig = `-- name: GetTLSConfig :one

SELECT id, enabled, cert_file, key_file, auto_cert, domains, created_at, updated_at FROM tls_config WHERE id = 1
`

// TLS config queries
func (q *Queries) GetTLSConfig(ctx context.Context) (*TlsConfig, error) {
	row := q.db.QueryRowContext(ctx, getTLSConfig)
	var i TlsConfig
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.CertFile,
		&i.KeyFile,
		&i.AutoCert,
		&i.Domains,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertTLSConfig = `-- name: UpsertTLSConfig :exec
INSERT INTO tls_config (id, enabled, cert_file, key_file, auto_cert, domains)
VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    enabled = excluded.enabled,
    cert_file = excluded.cert_file,
    key_file = excluded.key_file,
    auto_cert = excluded.auto_cert,
    domains = excluded.domains,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertTLSConfigParams struct {
	Enabled  sql.NullInt64  `json:"enabled"`
	CertFile sql.NullString `json:"cert_file"`
	KeyFile  sql.NullString `json:"key_file"`
	AutoCert sql.NullInt64  `json:"auto_cert"`
	Domains  sql.NullString `json:"domains"`
}

func (q *Queries) UpsertTLSConfig(ctx context.Context, arg *UpsertTLSConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertTLSConfig,
		arg.Enabled,
		arg.CertFile,
		arg.KeyFile,
		arg.AutoCert,
		arg.Domains,
	)
	return err
}
