// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whitelist.sql

package db

import (
	"context"
	"database/sql"
)

const createWhitelistEntry = `-- name: CreateWhitelistEntry :one
INSERT INTO ip_whitelist (id, ip_cidr, description, enabled)
VALUES (?, ?, ?, ?)
RETURNING id, ip_cidr, description, enabled, created_at
`

type CreateWhitelistEntryParams struct {
	ID          string         `json:"id"`
	IpCidr      string         `json:"ip_cidr"`
	Description sql.NullString `json:"description"`
	Enabled     sql.NullInt64  `json:"enabled"`
}

func (q *Queries) CreateWhitelistEntry(ctx context.Context, arg *CreateWhitelistEntryParams) (*IpWhitelist, error) {
	row := q.db.QueryRowContext(ctx, createWhitelistEntry,
		arg.ID,
		arg.IpCidr,
		arg.Description,
		arg.Enabled,
	)
	var i IpWhitelist
	err := row.Scan(
		&i.ID,
		&i.IpCidr,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteWhitelistEntry = `-- name: DeleteWhitelistEntry :exec
DELETE FROM ip_whitelist WHERE id = ?
`

func (q *Queries) DeleteWhitelistEntry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWhitelistEntry, id)
	return err
}

const getWhitelistByIP = `-- name: GetWhitelistByIP :one
SELECT id, ip_cidr, description, enabled, created_at FROM ip_whitelist WHERE ip_cidr = ?
`

func (q *Queries) GetWhitelistByIP(ctx context.Context, ipCidr string) (*IpWhitelist, error) {
	row := q.db.QueryRowContext(ctx, getWhitelistByIP, ipCidr)
	var i IpWhitelist
	err := row.Scan(
		&i.ID,
		&i.IpCidr,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
	)
	return &i, err
}

const getWhitelistEntry = `-- name: GetWhitelistEntry :one

SELECT id, ip_cidr, description, enabled, created_at FROM ip_whitelist WHERE id = ?
`

// IP whitelist queries
func (q *Queries) GetWhitelistEntry(ctx context.Context, id string) (*IpWhitelist, error) {
	row := q.db.QueryRowContext(ctx, getWhitelistEntry, id)
	var i IpWhitelist
	err := row.Scan(
		&i.ID,
		&i.IpCidr,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
	)
	return &i, err
}

const listEnabledWhitelist = `-- name: ListEnabledWhitelist :many
SELECT id, ip_cidr, description, enabled, created_at FROM ip_whitelist WHERE enabled = 1 ORDER BY created_at DESC
`

func (q *Queries) ListEnabledWhitelist(ctx context.Context) ([]*IpWhitelist, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledWhitelist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IpWhitelist{}
	for rows.Next() {
		var i IpWhitelist
		if err := rows.Scan(
			&i.ID,
			&i.IpCidr,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWhitelist = `-- name: ListWhitelist :many
SELECT id, ip_cidr, description, enabled, created_at FROM ip_whitelist ORDER BY created_at DESC
`

func (q *Queries) ListWhitelist(ctx context.Context) ([]*IpWhitelist, error) {
	rows, err := q.db.QueryContext(ctx, listWhitelist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IpWhitelist{}
	for rows.Next() {
		var i IpWhitelist
		if err := rows.Scan(
			&i.ID,
			&i.IpCidr,
			&i.Description,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWhitelistEntry = `-- name: UpdateWhitelistEntry :one
UPDATE ip_whitelist
SET ip_cidr = ?, description = ?, enabled = ?
WHERE id = ?
RETURNING id, ip_cidr, description, enabled, created_at
`

type UpdateWhitelistEntryParams struct {
	IpCidr      string         `json:"ip_cidr"`
	Description sql.NullString `json:"description"`
	Enabled     sql.NullInt64  `json:"enabled"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateWhitelistEntry(ctx context.Context, arg *UpdateWhitelistEntryParams) (*IpWhitelist, error) {
	row := q.db.QueryRowContext(ctx, updateWhitelistEntry,
		arg.IpCidr,
		arg.Description,
		arg.Enabled,
		arg.ID,
	)
	var i IpWhitelist
	err := row.Scan(
		&i.ID,
		&i.IpCidr,
		&i.Description,
		&i.Enabled,
		&i.CreatedAt,
	)
	return &i, err
}
