// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: router.proto

package plugin

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// RouterPluginServiceClient 是路由插件服务的客户端接口
type RouterPluginServiceClient interface {
	Info(ctx context.Context, in *PluginInfo, opts ...grpc.CallOption) (*PluginInfo, error)
	Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error)
}

type routerPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterPluginServiceClient(cc grpc.ClientConnInterface) RouterPluginServiceClient {
	return &routerPluginServiceClient{cc}
}

func (c *routerPluginServiceClient) Info(ctx context.Context, in *PluginInfo, opts ...grpc.CallOption) (*PluginInfo, error) {
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, "/routerplugin.RouterPlugin/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerPluginServiceClient) Match(ctx context.Context, in *MatchRequest, opts ...grpc.CallOption) (*MatchResponse, error) {
	out := new(MatchResponse)
	err := c.cc.Invoke(ctx, "/routerplugin.RouterPlugin/Match", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterPluginServiceServer 是路由插件服务的服务端接口
type RouterPluginServiceServer interface {
	Info(context.Context, *PluginInfo) (*PluginInfo, error)
	Match(context.Context, *MatchRequest) (*MatchResponse, error)
}

// UnimplementedRouterPluginServiceServer 用于未实现的方法
type UnimplementedRouterPluginServiceServer struct{}

func (UnimplementedRouterPluginServiceServer) Info(context.Context, *PluginInfo) (*PluginInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedRouterPluginServiceServer) Match(context.Context, *MatchRequest) (*MatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Match not implemented")
}

func RegisterRouterPluginServiceServer(s grpc.ServiceRegistrar, srv RouterPluginServiceServer) {
	s.RegisterService(&RouterPluginService_ServiceDesc, srv)
}

func _RouterPluginService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterPluginServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerplugin.RouterPlugin/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterPluginServiceServer).Info(ctx, req.(*PluginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterPluginService_Match_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterPluginServiceServer).Match(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/routerplugin.RouterPlugin/Match",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterPluginServiceServer).Match(ctx, req.(*MatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterPluginService_ServiceDesc 描述服务
var RouterPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routerplugin.RouterPlugin",
	HandlerType: (*RouterPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _RouterPluginService_Info_Handler,
		},
		{
			MethodName: "Match",
			Handler:    _RouterPluginService_Match_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}